eval_config:
  use_cuda: True # Use GPU if available
  batch_size: 128
  dataset: 'FMNIST'
  checkpoint: 'default'
  

model_config:
  inf_type: 'rep' # 'uncoded' for the uncoded case, 'rep' for the coded case with inference at bit level using repetition codes, 'hier' for the coded hierarchical case.
  likelihood: 'ber' # Distribution used to compute the reconstruction term: 'gauss' for Gaussian likelihood, 'ber' for Bernoulli likelihood.
  bits_info: 8 
  bits_code: 80
  code_file: 'default'
  beta: 15
  type_encoder: 'dcgan'
  type_decoder: 'cnnskip'